# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 07:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_zh', models.CharField(max_length=100, unique=True)),
                ('updated', models.DateTimeField()),
                ('author', models.CharField(max_length=100, unique=True)),
                ('content_md', models.TextField()),
                ('content_html', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=[':D'], size=None)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=[':D'], size=None)),
                ('views', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
