# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170608_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summery',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
