# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_summery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summery',
            new_name='summary',
        ),
    ]
